# Generated by Django 6.0.2 on 2026-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_player_image_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
