# Generated by Django 6.0.2 on 2026-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='temp', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
