# Generated by Django 6.0.2 on 2026-04-18 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='is_unsold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
