# Generated by Django 6.0.2 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_player_created_at_player_is_unsold_player_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_retained',
            field=models.BooleanField(default=False),
        ),
    ]
