# Generated by Django 6.0.2 on 2026-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_player_is_retained'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='retain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='purse',
            field=models.IntegerField(default=35000),
        ),
    ]
