# Generated by Django 6.0.2 on 2026-04-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_player_image_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='round_number',
            field=models.IntegerField(choices=[(1, 'Round 1'), (2, 'Re-Auction')], default=1),
        ),
    ]
